name = "piv-prog-site"
compatibility_date = "2026-10-07"
main = "./worker.js"

[vars]
API_ORIGIN = "http://79.137.202.111:4173"

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = ["/api/*"]
